import { test, expect } from '@playwright/test'

let homePage = "http://localhost:3000";

test.beforeAll(async () => {
    console.log('Before tests');
});

test.afterAll(async () => {
    console.log('After tests');
});

test.describe('Checking heading', () => {
    test('The title tag', async({ page }) => {
        await page.goto(homePage)

        await expect(page).toHaveTitle('Flowerpedia - Home');
    })

    test('The meta tag', async ({ page }) => { 
        await page.goto(homePage)
        
        const metaDescriptionOne = page.locator('meta[name="Flower Mini-Site"]')
        await expect(metaDescriptionOne).toHaveAttribute("content", "Generated by create next app")
    })

    test('The link tag', async ({ page }) => {
        await page.goto(homePage)

        const linkTag = page.locator('link[rel="icon"]');
        await expect(linkTag).toHaveAttribute('href', '/Flower Bouquet.png')
    })
})