import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

import ImageCard from '../components/ImageCard'
import InfoCard from '../components/InfoCard'
import Button from '../components/Button'
import CircleImage from '../components/CircleImage'

export default function Home() {

  const [info, setInfo]= useState(false)

  return (
    <div className={styles.container}>
      <Head>
        <title>Flowers 101</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Flower Bouquet.png" />
      </Head>

      <main className={styles.main}>

        <CircleImage/>
        <h1> Flowers </h1>
        <Button/>
        
        <div onClick={() => setInfo(!info)}>
        <ImageCard/>
        </div>
        {info ? <InfoCard/> : null}  

        
      </main>
    </div>
  )
}
