import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

import Text from '../components/Text'
import ImageCard from '../components/ImageCard'
import InfoCard from '../components/InfoCard'
import Button from '../components/Button'
import CircleImage from '../components/CircleImage'
import record from '../Database/flower-database.json'

export default function Home() {

  const [info, setInfo]= useState(false)

  return (
    <main className={styles.Wrapper}>
      <Head>
        <title>Flowers 101</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Flower Bouquet.png" />
      </Head>

      <div>

        <div className={styles.Header}>
        <a href="/"><Button txt='Back'/></a>
        </div>

        <Text padding='40px' size='40px' weight='700' txt='Spring Flowers'/>
        <div className={styles.Data}>
        {
          record.map((rec, index) => {
            return (
              <>
                <>{rec.BloomsIn == "Spring" ?<div onClick={() => setInfo(!info)} key={index}>
                       <ImageCard Name={rec.Name} Type={rec.PlantType} src={rec.Image}/>
                       {info ? <InfoCard descp={rec.Desc} soil={rec.SoilNeeds} height={rec.Height} sun={rec.SunNeeds} water={rec.WaterNeeds} care={rec.Maintenance} /> : null}
                       </div> : <></>}</>
                </>
            )
          })
        }
        </div>

        
      </div>
    </main>
  )
}
